### ISSUE TITLE
Use libfreeipmi directly instead of parsing ipmitool shell output

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/ipmi-fan-control#50]
ipmi-fan-control currently invokes a long-lived `ipmitool shell` session for sending commands and parsing information out of the human-readable output. While it works decently well, it's quite fragile. It depends on ipmitool's output format never changing and IPMI errors currently aren't reliably detected.

With libfreeipmi, we'll have a proper library to interact with. I don't intend to create a full Rust binding for libfreeipmi though--it's too much work. We'll generate FFI wrappers via bindgen + pkg-config (for finding libfreeipmi) and only use the few functions we need.

The configuration will remain exactly the same for local connections (the default setup). The remote session configuration will change though. Instead of providing command line arguments, like:
```toml
[sessions]
"foobar" = ["-I", "lanplus", "-H", "<host>", "-U", "<username>", "-P", "<password>"]
```
it'll be more like:
```toml
[sessions]
"foobar" = { type = "remote", host = "<host>", username = "<username>", password = "<password>" }
```

I'll consider adding backwards compatibility for the old syntax with ipmitool's CLI args, but at most, it'll only support `-I lanplus`, `-H`, `-U`, and `-P`.
